sample-datafold-dbt-project:
  target: prod
  outputs:
    prod:
      type: snowflake
      user: "{{ env_var('DBT_USER') }}"
      password: "{{ env_var('DBT_PASSWORD') }}"
      database: "{{ env_var('DBT_DATABASE') }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: 1
      warehouse: "{{ env_var('DBT_WAREHOUSE') }}"
      account: "{{ env_var('DBT_SNOWFLAKE_ACCOUNT') }}"
      role: "{{ env_var('DBT_ROLE') }}"