name: Check DBT Models

on:
  pull_request:
  push:
    branches:
      - main
jobs:
  dbt_test:
    concurrency: test_database
    env:
      DBT_DATABASE: ${{ secrets.DBT_DATABASE }}
      DBT_SCHEMA: ${{ secrets.DBT_SCHEMA }}
      DBT_WAREHOUSE: ${{ secrets.DBT_WAREHOUSE }}
      DBT_PROFILES_DIR: "${{ github.workspace }}/dbt/profiles"
      DBT_ROLE: ${{ secrets.DBT_ROLE }}
      DBT_USER: ${{ secrets.DBT_USER }}
      DBT_PASSWORD: ${{ secrets.DBT_PASSWORD }}
      DBT_SNOWFLAKE_ACCOUNT: ${{ secrets.DBT_SNOWFLAKE_ACCOUNT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: "actions/setup-python@v2"
        with:
            python-version: "3.11"
      - name: Install dependencies
        run: "pip install -r requirements-dbt.txt"
      - name: Run DBT test
        working-directory: ./dbt
        run: |
          dbt deps --profiles-dir ./profiles
          dbt compile --profiles-dir ./profiles
      - name: Install Datafold SDK
        run: pip install -q datafold-sdk
      - name: Upload dbt artifacts to Datafold
        run: datafold dbt upload --ci-config-id 337 --run-type production --target-folder './dbt/target' --commit-sha ${GIT_SHA}
        env:
          DATAFOLD_APIKEY: ${{ secrets.DATAFOLD_API_KEY }}
          DATAFOLD_API_KEY: ${{ secrets.DATAFOLD_API_KEY }}
          GIT_SHA: "${{ github.sha }}"
